#!/usr/bin/env bash
#salam

while IFS=':' read -r username password uid group info home cmshell
do
echo "The user $username is part of the $group gang, lives in $home and rides $cmshell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
