#!/usr/bin/env bash
#bezmeduy
i=1

while [ $i -le 20 ]; do
    case $i in
        4)
            echo "$i"
            echo "Bad luck from China"
            ;;
        9)
            echo "$i"
            echo "Bad luck from Japan"
            ;;
        17)
            echo "$i"
            echo "Bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    ((i++))
done

