#!/usr/bin/env bash
#aha

FILE_NAME="school"

if [ -e "$FILE_NAME" ]; then
    echo "school file exists"

    if [ -s "$FILE_NAME" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f "$FILE_NAME" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
