#!/usr/bin/env bash
#salaaam

PID_FILE="/var/run/my_process.pid"
PROCESS="./manage_my_process"

case "$1" in
  start)
    $PROCESS &
    echo $! > $PID_FILE
    echo "manage_my_process started"
    ;;
  stop)
    [ -f $PID_FILE ] && kill $(cat $PID_FILE) && rm $PID_FILE
    echo "manage_my_process stopped"
    ;;
  restart)
    [ -f $PID_FILE ] && kill $(cat $PID_FILE) && rm $PID_FILE
    $PROCESS &
    echo $! > $PID_FILE
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
