#!/usr/bin/env bash
# shellcheck disable=SC2009

pid=$(pgrep -f '4-to_infinity_and_beyond' | grep -v "$$")

# If a PID was found, send SIGTERM to it
if [ -n "$pid" ]; then
    # Write the signal to the process' /proc entry – no kill/killall
fi
